#!/usr/bin/env python3
"""Generate name_overrides.py (NAME_OVERRIDE + NAME_AUTO_OVERRIDE) from name_results.txt + original knowns.

NAME_OVERRIDE      id-keyed, rule id < AUTO_MIN (source/official-derived ids: stable)
NAME_AUTO_OVERRIDE registrable-domain-keyed, auto id range >= AUTO_MIN (build_rules.py
                   allocates auto ids sequentially in sorted-first-host order, so adding
                   a registrable shifts every later auto id — id keys would go stale and
                   can collide with the fixed MANUAL ids 20546-20550)
"""
import ast
import os
import re

TMP = os.environ.get("OAF_TMP", "/var/folders/6p/34qnc0t57jdcnjhjfbdxm63h0000gn/T/opencode")
AUTO_MIN = 20433   # build_rules.py auto id allocator starts here

ORIG = {    # source rule id -> name (id < AUTO_MIN)
    20124: "哔哩哔哩", 20127: "Barnes & Noble", 20234: "盒马", 20235: "盒马",
    20244: "一点资讯", 20279: "欧可林", 20284: "grep.app", 20311: "柏林工业大学",
    20422: "乐播投屏",
}
ORIG_AUTO = {   # auto-range id -> (representative domain, name): built-ins not in name_results
    20434: ("118114.net", "中国电信118114"), 20452: ("appcenter.ms", "微软AppCenter"),
    20477: ("fastly-edge.com", "Fastly"), 20484: ("iconfont.cn", "Iconfont"),
    20485: ("imgcook.com", "Imgcook"), 20497: ("mzstatic.com", "苹果服务"),
}
BAD = re.compile(r"[#~:;,\[\]]")
RES = f"{TMP}/name_results.txt"

# lift PSL2 + registrable() from build_rules.py via AST (a plain import would
# execute the whole build script) — guarantees identical domain keying
_here = os.path.dirname(os.path.abspath(__file__))
_tree = ast.parse(open(os.path.join(_here, "build_rules.py"), encoding="utf-8").read())
_ns = {}
for _node in _tree.body:
    if isinstance(_node, ast.Assign) and any(getattr(t, "id", "") == "PSL2" for t in _node.targets):
        exec(compile(ast.Module([_node], []), "build_rules.py", "exec"), _ns)
    elif isinstance(_node, ast.FunctionDef) and _node.name == "registrable":
        exec(compile(ast.Module([_node], []), "build_rules.py", "exec"), _ns)
registrable = _ns["registrable"]

ov = dict(ORIG)         # id -> name (id < AUTO_MIN)
auto = {}               # registrable -> name (auto range)
for rid, (dom, name) in ORIG_AUTO.items():
    auto[registrable(dom)] = name
keeps = []
errs = []
n = 0
for raw in open(RES, encoding="utf-8"):
    raw = raw.strip()
    if not raw:
        continue
    n += 1
    m = re.match(r"^(\d{5}) (\S+) → (\S+) \| (\S+) \| (.*)$", raw)
    if not m:
        errs.append(f"parse: {raw}")
        continue
    rid, dom, name, conf, ev = int(m.group(1)), m.group(2), m.group(3), m.group(4), m.group(5)
    if conf == "KEEP" or name == "KEEP":
        keeps.append((rid, dom))
        continue
    if BAD.search(name):
        errs.append(f"bad charset {rid}: {name}")
        continue
    if len(name) > 40:
        errs.append(f"name too long {rid}: {name}")
        continue
    if rid < AUTO_MIN:
        if rid in ov and ov[rid] != name:
            errs.append(f"conflict {rid}: {ov[rid]} vs {name}")
            continue
        ov[rid] = name
        continue
    reg = registrable(dom)
    if reg != dom:
        print(f"NOTE {rid} {dom} -> registrable {reg}")
    if reg in auto and auto[reg] != name:
        errs.append(f"conflict reg {reg}: {auto[reg]} vs {name} ({rid} {dom})")
        continue
    auto[reg] = name

print(f"input lines {n}, keeps {len(keeps)}, id overrides {len(ov)} (<{AUTO_MIN}), "
      f"auto overrides {len(auto)} (domain-keyed)")
if errs:
    print("ERRORS:")
    for e in errs:
        print(" ", e)
    raise SystemExit(1)

lines = ["# generated by gen_name_overrides.py -- do not edit",
         "NAME_OVERRIDE = {   # source rule id -> friendly name (researched; KEEP = domain kept as-is)"]
for rid in sorted(ov):
    lines.append(f"    {rid}: {ov[rid]!r},")
lines.append("}")
lines.append("")
lines.append(f"NAME_AUTO_OVERRIDE = {{   # registrable domain -> friendly name (auto id range >= "
             f"{AUTO_MIN}: ids shift when new registrables appear, so key by domain)")
for reg in sorted(auto):
    lines.append(f"    {reg!r}: {auto[reg]!r},")
lines.append("}")
out = os.path.join(_here, "name_overrides.py")
open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"wrote {out} ({len(lines)} lines)")
print("KEEP (stay domain-named):", ", ".join(f"{r} {d}" for r, d in keeps))
